### ISSUE TITLE
Proposal: `Cached a` newtype?

### ISSUE THREAD

**Issue by JackKelly-Bellroy** [bellroy/haskell-cached-io#14]
The type signature for `cachedIO` is currently:

```haskell
cachedIO :: (MonadIO m, MonadIO t, MonadCatch t) => NominalDiffTime -> t a -> m (t a)
```

It's tempting to immediately use `join` on this to get an `m a` if the monads line up, but that means you don't get any caching at all: if you store the returned `IO a` in a data structure, each invocation will set up a new cache for the value. Would this design be better?

```haskell
newtype Cached t a = Cached { runCached :: t a }
cachedIO :: (MonadIO m, MonadIO t, MonadCatch t) => NominalDiffTime -> t a -> m (Cached t a)
```

It'd be harder to accidentally `join` the construction of the caching value with the fetch/refetch action.

**Comment by kokobd** [comment]
I think it's a good idea, if we can't come up with a more type safe approach that strictly guarantees it?

For uncareful people, it's not hard to do `let z = join . fmap (view #runCached) $ cacheIO x y`

**Comment by JackKelly-Bellroy** [comment]
My view is that it's often best to make libraries hard but not impossible to use wrong, because locking out that last 5% or so of "wrong ways" often causes a big explosion in boilerplate and/or advanced type system stuff. A dev who is that determined to run a cached action right now will know what that means.
